title = "Lucky Blocks"

download = "https://modrinth.com/datapack/lucky-blocks"

youtube = '<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/Br87So1Ouag" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>'

description = """My lucky blocks datapack was a very big porject for me at the time, and remains my most popular datapack to date. This particular datapack holds a special place in my heart, as it marked the beginning of my journey as a Minecraft content creator on YouTube. <br/>
<br/>
There are 5 tiers of lucky blocks: Coal up to Netherite. Each one holds better rewards, but also bigger dangers. Upon breaking a Lucky Block, you might be showered with valuable treasures, ranging from rare resources like diamonds and emeralds to powerful enchanted items. Alternatively, you might find yourself facing unexpected challenges as waves of mobs descend upon you or treacherous traps are sprung.<br/>
<br/>
The main reason this datapack took so much effort to make was that I had to create my own custom crafting table, so that the lucky blocks were easily craftable. I'm very thankful I did so though, because I have used the crafter in many datapacks since."""
